#!/bin/sh

# Written in 2016 by Evan Prodromou <evan@fuzzy.ai>
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with
# this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -e

if [ -z ${HOST+x} ]; then
  echo "HOST environment variable is required"
  exit 1
fi

if [ -z ${DATABASE+x} ]; then
  echo "DATABASE environment variable is required"
  exit 1
fi

TMPDIR=/tmp/backup
BACKUPDIR=/backup

/usr/bin/mongodump -h $HOST -d $DATABASE -o $TMPDIR
tar zcvf ${BACKUPDIR}/${DATABASE}-$(date -u +"%Y-%m-%d").tar.gz $TMPDIR/$DATABASE
rm -Rf $TMPDIR/$DATABASE
