# Written in 2016 by Evan Prodromou <evan@fuzzy.ai>
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with
# this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

version: '2'
services:
  foobar:
    image: mongo:3.2
  backup:
    build: .
    links:
    - foobar:foobar
    volumes:
     - ./backup:/backup
    environment:
      HOST: foobar
      DATABASE: bazquux
